# Generated by Django 5.0.1 on 2024-01-11 11:18

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_mguser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='mguser',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
    ]
