# Generated by Django 5.0.1 on 2024-01-11 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_mguser_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='mguser',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
