# Generated by Django 5.0.1 on 2024-01-11 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_mguser_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mguser',
            name='verified',
            field=models.BooleanField(default=False, help_text='If the user has been verified - Patient by Doctor, Doctor by Admin'),
        ),
    ]
