# Generated by Django 5.0.1 on 2024-01-13 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_demographics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demographics',
            name='patient_profile',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='demographics', to='patient.patientprofile'),
        ),
    ]
