# Generated by Django 5.0.1 on 2024-01-13 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_mguser_verified'),
        ('patient', '0007_alter_demographics_patient_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='first_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_updated_by', to='accounts.doctor'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='first_updated_by_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='last_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_updated_by', to='accounts.doctor'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='last_updated_by_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='updated',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='MedicalCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_code', models.CharField(max_length=20)),
                ('patient_profile', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='medical_conditions', to='patient.patientprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ConcomitantMedication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_profile', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='concomitant_medications', to='patient.patientprofile')),
                ('medical_condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.medicalcondition')),
            ],
        ),
    ]
