# Generated by Django 5.0.1 on 2024-01-13 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0009_alter_medicalcondition_condition_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalcondition',
            name='condition_code',
            field=models.CharField(max_length=20),
        ),
    ]
