# Generated by Django 5.0.1 on 2024-01-13 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0010_alter_medicalcondition_condition_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalcondition',
            old_name='condition_code',
            new_name='ICD10_code',
        ),
    ]
