# Generated by Django 5.0.1 on 2024-01-13 14:09

import accounts.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0011_rename_condition_code_medicalcondition_icd10_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='concomitantmedication',
            name='drug_inn',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='demographics',
            name='date_of_birth',
            field=models.DateField(null=True, validators=[accounts.utils.validate_dob]),
        ),
    ]
