# Generated by Django 5.0.1 on 2024-01-13 14:09

import accounts.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0012_concomitantmedication_drug_inn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concomitantmedication',
            name='drug_inn',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='demographics',
            name='date_of_birth',
            field=models.DateField(validators=[accounts.utils.validate_dob]),
        ),
    ]
