# Generated by Django 5.0.1 on 2024-01-13 14:13

import accounts.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0015_alter_demographics_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demographics',
            name='date_of_birth',
            field=models.DateField(null=True, validators=[accounts.utils.validate_dob]),
        ),
    ]
