# Generated by Django 5.0.1 on 2024-01-13 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0016_alter_demographics_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalcondition',
            name='disease_description',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
