# Generated by Django 5.0.1 on 2024-01-13 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0017_medicalcondition_disease_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalcondition',
            name='disease',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
