# Generated by Django 5.0.1 on 2024-01-17 17:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0019_alter_patientprofile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='concomitantmedication',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2024, 1, 17, 17, 24, 42, 401413, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='concomitantmedication',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 1, 17, 17, 24, 52, 883395, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalcondition',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2024, 1, 17, 17, 24, 57, 786631, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalcondition',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 1, 17, 17, 25, 7, 623334, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
