# Generated by Django 5.0.1 on 2024-01-17 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0020_concomitantmedication_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concomitantmedication',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalcondition',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
