# Generated by Django 4.2.9 on 2024-01-21 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0021_alter_concomitantmedication_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demographics',
            name='gender_at_birth',
            field=models.CharField(choices=[('m', 'Male'), ('f', 'Female')], max_length=1, null=True),
        ),
    ]
