# Generated by Django 4.2.9 on 2024-01-21 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0024_remove_demographics_relationship_to_patient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demographics',
            name='allergies',
            field=models.CharField(help_text='List the allergies the patient has if any or type None if none.', max_length=250, null=True),
        ),
    ]
