# Generated by Django 5.0.1 on 2024-01-10 17:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_alter_mguser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret', models.UUIDField(default=uuid.uuid4, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Consent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('signed', models.BooleanField(default=False)),
                ('date_signed', models.DateTimeField()),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consents_doctor', to='accounts.doctor')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consents_patient', to='accounts.patient')),
                ('qr_code', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conset_qr', to='consent.qrcode')),
            ],
        ),
        migrations.CreateModel(
            name='EcrfConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consent.consent')),
            ],
        ),
    ]
