# Generated by Django 5.0.1 on 2024-01-10 21:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_mguser_role'),
        ('consent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consent',
            name='date_signed',
            field=models.DateTimeField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='consent',
            name='patient',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='consents_patient', to='accounts.patient'),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='secret',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
