# Generated by Django 5.0.1 on 2024-01-10 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consent', '0002_alter_consent_date_signed_alter_consent_patient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consent',
            name='date_signed',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
