# Generated by Django 5.0.1 on 2024-01-10 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_mguser_role'),
        ('consent', '0003_alter_consent_date_signed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consent',
            name='patient',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consents_patient', to='accounts.patient'),
        ),
    ]
