# Generated by Django 5.0.1 on 2024-01-10 22:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consent', '0006_alter_consent_doctor_alter_consent_patient_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='consent',
            name='doctor',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='consents_doctor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='consent',
            name='patient',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consents_patient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='consent',
            name='qr_code',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='conset_qr', to='consent.qrcode'),
        ),
        migrations.AlterField(
            model_name='consent',
            name='signed',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='ecrfconsent',
            name='consent',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='consent.consent'),
        ),
    ]
