# Generated by Django 5.0.1 on 2024-01-10 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consent', '0007_alter_consent_doctor_alter_consent_patient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecrfconsent',
            name='signed',
            field=models.BooleanField(default=False),
        ),
    ]
