# Generated by Django 5.0.1 on 2024-01-11 00:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consent', '0009_ecrfconsent_date_created_ecrfconsent_date_modified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecrfconsent',
            name='consent',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='ecrf_consents', to='consent.consent'),
        ),
        migrations.AlterField(
            model_name='ecrfconsent',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
