# Generated by Django 5.0.1 on 2024-01-11 21:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consent', '0010_alter_ecrfconsent_consent_alter_ecrfconsent_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='consent',
            name='doctor',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='ConsentsDoctor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='consent',
            name='patient',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ConsentsPatient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='consent',
            name='qr_code',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='ConsentQRCode', to='consent.qrcode'),
        ),
        migrations.AlterField(
            model_name='ecrfconsent',
            name='consent',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='EcrfConsents', to='consent.consent'),
        ),
    ]
