# Generated by Django 5.0.1 on 2024-01-14 11:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consent', '0011_alter_consent_doctor_alter_consent_patient_and_more'),
        ('trial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrialConsent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('signed', models.BooleanField(default=False)),
                ('date_signed', models.DateTimeField(blank=True, editable=False, null=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('consent', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='EcrfConsents', to='consent.consent')),
                ('trial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trials_ecrfconsents', to='trial.trial')),
            ],
        ),
        migrations.DeleteModel(
            name='EcrfConsent',
        ),
    ]
