# Generated by Django 5.0.1 on 2024-01-14 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consent', '0012_trialconsent_delete_ecrfconsent'),
        ('trial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trialconsent',
            name='consent',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='TrialConsents', to='consent.consent'),
        ),
        migrations.AlterField(
            model_name='trialconsent',
            name='trial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trial_trialconsents', to='trial.trial'),
        ),
    ]
