# Generated by Django 4.2.9 on 2024-01-30 23:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import files.models


class Migration(migrations.Migration):
    dependencies = [
        ("consent", "0013_alter_trialconsent_consent_alter_trialconsent_trial"),
    ]

    operations = [
        migrations.AddField(
            model_name="qrcode",
            name="consent",
            field=models.ForeignKey(
                default=None,  # Set an appropriate default value for the ForeignKey field
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="TrialQRCodes",
                to="consent.consent",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="qrcode",
            name="qr_code",
            field=models.ImageField(
                default=None,  # Set an appropriate default value for the ImageField field
                upload_to=files.models.qr_code_directory_path,
            ),
            preserve_default=False,
        ),
    ]
