# Generated by Django 4.2.9 on 2024-01-30 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consent', '0015_alter_qrcode_consent_alter_qrcode_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcode',
            name='consent',
        ),
        migrations.RemoveField(
            model_name='qrcode',
            name='qr_code',
        ),
    ]
