# Generated by Django 4.2.9 on 2024-01-30 23:18

from django.db import migrations, models
import django.db.models.deletion
import files.models


class Migration(migrations.Migration):

    dependencies = [
        ('consent', '0016_remove_qrcode_consent_remove_qrcode_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='consent',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TrialQRCodes', to='consent.consent'),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='qr_code',
            field=models.ImageField(null=True, upload_to=files.models.qr_code_directory_path),
        ),
    ]
