# Generated by Django 4.2.9 on 2024-02-06 11:48

from django.db import migrations, models
import django.db.models.deletion
import files.models


class Migration(migrations.Migration):

    dependencies = [
        ('trial', '0001_initial'),
        ('consent', '0017_qrcode_consent_qrcode_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='qr_code',
            field=models.ImageField(editable=False, null=True, upload_to=files.models.qr_code_directory_path),
        ),
        migrations.AlterField(
            model_name='trialconsent',
            name='trial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TrialTrialConsents', to='trial.trial'),
        ),
    ]
