# Generated by Django 4.2.9 on 2024-01-30 23:11

import django.core.validators
from django.db import migrations, models
import files.models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to=files.models.user_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'png', 'jpg', 'jpeg', 'gif'])]),
        ),
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(editable=False, max_length=255),
        ),
    ]
