# Generated by Django 5.0.1 on 2024-01-11 22:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='doctor_user',
            field=models.OneToOneField(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='DoctorProfiles', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
