# Generated by Django 5.0.1 on 2024-01-11 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_mguser_verified'),
        ('doctor', '0002_remove_doctorprofile_user_doctorprofile_doctor_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='doctor_user',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='DoctorProfiles', to='accounts.doctor'),
        ),
    ]
