# Generated by Django 4.2.9 on 2024-01-21 15:32

import accounts.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_alter_doctorprofile_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalSpecialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='date_of_birth',
            field=models.DateField(null=True, validators=[accounts.utils.validate_dob]),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='gender_at_birth',
            field=models.CharField(choices=[('m', 'Male'), ('f', 'Female')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='license_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='years_of_experience',
            field=models.CharField(choices=[('0-5', '0-5 Years'), ('6-10', '6-10 Years'), ('11-15', '11-15 Years'), ('16+', '16+ Years')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='medical_specialties',
            field=models.ManyToManyField(related_name='doctor_profiles', to='doctor.medicalspecialty'),
        ),
    ]
