# Generated by Django 4.2.9 on 2024-01-21 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0006_medicalspecialty_doctorprofile_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicalspecialty',
            options={'verbose_name_plural': 'Medical Specialties'},
        ),
    ]
