# Generated by Django 4.2.9 on 2024-01-21 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0007_alter_medicalspecialty_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='address',
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='working_address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='phone_number',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='postal_code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='state',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
