# Generated by Django 4.2.9 on 2024-01-21 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0008_remove_doctorprofile_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='first_update',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='working_address',
            field=models.CharField(help_text='The address where patients can find you.', max_length=100, null=True),
        ),
    ]
