# Generated by Django 5.0.1 on 2024-01-14 11:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0007_alter_mguser_verified'),
        ('trial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ecrf',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecrf_doctor', to='accounts.doctor')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ecrf_patient', to='accounts.patient')),
                ('trial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trial_ecrfs', to='trial.trial')),
            ],
        ),
    ]
