# Generated by Django 5.0.1 on 2024-01-17 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecrf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('F2F', 'Face to face'), ('PHONE', 'Phone')], default='F2F', max_length=20)),
                ('ecrf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecrf_visits', to='ecrf.ecrf')),
            ],
        ),
        migrations.CreateModel(
            name='AdverseEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adverse_event', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('ecrf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecrf_adverse_events', to='ecrf.ecrf')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_adverse_events', to='ecrf.visit')),
            ],
        ),
        migrations.CreateModel(
            name='FirstVisit',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ecrf.visit',),
        ),
        migrations.CreateModel(
            name='LastVisit',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ecrf.visit',),
        ),
    ]
