# Generated by Django 5.0.1 on 2024-01-17 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecrf', '0002_visit_adverseevent_firstvisit_lastvisit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adverseevent',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
