# Generated by Django 5.0.1 on 2024-01-18 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecrf', '0003_alter_adverseevent_end_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FirstVisit',
        ),
        migrations.DeleteModel(
            name='LastVisit',
        ),
    ]
