# Generated by Django 5.0.1 on 2024-01-18 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecrf', '0006_visit_post_study'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='serial',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
