# Generated by Django 5.0.1 on 2024-01-18 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecrf', '0007_alter_visit_serial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visit',
            old_name='date',
            new_name='date_created',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='serial',
        ),
        migrations.AddField(
            model_name='visit',
            name='pre_study',
            field=models.BooleanField(default=False),
        ),
    ]
