# Generated by Django 4.2.9 on 2024-02-06 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_alter_file_file_alter_file_name'),
        ('ecrf', '0008_rename_date_visit_date_created_remove_visit_serial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='files',
            field=models.ManyToManyField(to='files.file'),
        ),
    ]
