# Generated by Django 4.2.9 on 2024-02-07 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecrf', '0009_visit_files'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ecrf',
            constraint=models.UniqueConstraint(fields=('patient', 'trial'), name='unique_patient_trial_ecrf'),
        ),
    ]
